server:
  port: 8081
  servlet:
    context-path: /api/orchestrator

spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://postgres_service:5432/test_db
    username: user_test
    password: password_test
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

kafka:
  topic: order-topic
  topic_grouped_id: order-group
  bootstrap_server_config: kafka_service:9092
  retries_config: 5
  topic_retry: order-topic-retry
  topic_retry_grouped_id: order-group-retry
  retries_config_topic: 5
